/**
 * Kadesh Codex Apps Script write-back prototype configuration.
 *
 * This version is aligned to the current live Google Sheet tab/header schema
 * provided during prototype setup.
 */

const KADESH_CONFIG = {
  apiVersion: "prototype-0.3",

  /**
   * ScriptProperties expected before deployment:
   * - KADESH_SPREADSHEET_ID: canonical Google Sheet ID to write to
   * - KADESH_ALLOWED_WRITERS: comma-separated writer emails; optional during local testing
   * - KADESH_SHARED_SECRET: optional fallback token for non-domain deployments
   * - KADESH_FOLDER_POI_IMAGES: Drive folder ID for POI images
   * - KADESH_FOLDER_NPC_IMAGES: Drive folder ID for NPC images
   * - KADESH_FOLDER_MAP_IMAGES: Drive folder ID for map images
   * - KADESH_FOLDER_REGION_IMAGES: Drive folder ID for region images
   * - KADESH_FOLDER_POI_GROUP_IMAGES: Drive folder ID for POI group images
   * - KADESH_FOLDER_MISC_UPLOADS: fallback Drive folder ID
   */
  scriptProperties: {
    spreadsheetId: "KADESH_SPREADSHEET_ID",
    allowedWriters: "KADESH_ALLOWED_WRITERS",
    sharedSecret: "KADESH_SHARED_SECRET",
    folders: {
      regionImage: "KADESH_FOLDER_REGION_IMAGES",
      poiImage: "KADESH_FOLDER_POI_IMAGES",
      poiGroupImage: "KADESH_FOLDER_POI_GROUP_IMAGES",
      npcImage: "KADESH_FOLDER_NPC_IMAGES",
      mapImage: "KADESH_FOLDER_MAP_IMAGES",
      misc: "KADESH_FOLDER_MISC_UPLOADS"
    }
  },

  /**
   * Current live Sheet ID supplied for prototype use:
   * 1vb-y-jgWLUIhDstZwObQph_lfJUkVhhEKuln4OuORvo
   *
   * Store it as ScriptProperty KADESH_SPREADSHEET_ID rather than hard-coding
   * it here, so the same code can be tested against clones.
   */
  entities: {
    region: {
      label: "Region",
      sheetName: "Regions",
      idField: "Region_ID",
      idPrefix: "REG-",
      idPadding: 3,
      requiredCreateFields: ["Region_Name"],
      allowedCreateFields: ["Region_ID", "Region_Name", "Lore", "Image"],
      allowedUpdateFields: ["Region_Name", "Lore", "Image"],
      assetField: "Image",
      assetFolderKey: "regionImage"
    },

    /**
     * Hex IDs are coordinate IDs such as "300:300" and are not safely
     * auto-generated by a simple numeric sequence. Create requests for hexes
     * must provide Hex_ID explicitly.
     */
    hex: {
      label: "Hex",
      sheetName: "Hexes",
      idField: "Hex_ID",
      manualId: true,
      requiredCreateFields: ["Hex_ID", "Region_ID_Ref", "Terrain", "Map_XY"],
      allowedCreateFields: ["Hex_ID", "Region_ID_Ref", "Terrain", "Map_XY"],
      allowedUpdateFields: ["Region_ID_Ref", "Terrain", "Map_XY"]
    },

    poi: {
      label: "POI",
      sheetName: "POIs",
      idField: "POI_ID",
      idPrefix: "POI-",
      idPadding: 4,
      requiredCreateFields: ["Name"],
      allowedCreateFields: [
        "POI_ID", "POI_Group_ID", "Name", "Hex_ID_Ref", "POI_Type",
        "Notoriety Tier", "Population", "Lore", "Image"
      ],
      allowedUpdateFields: [
        "POI_Group_ID", "Name", "Hex_ID_Ref", "POI_Type",
        "Notoriety Tier", "Population", "Lore", "Image"
      ],
      assetField: "Image",
      assetFolderKey: "poiImage"
    },

    /**
     * POI group IDs are semantic keys such as "ERIKOL", not generated
     * numeric IDs. Create requests must provide POI_Group_ID explicitly.
     */
    poiGroup: {
      label: "POI Group",
      sheetName: "POI_Groups",
      idField: "POI_Group_ID",
      manualId: true,
      requiredCreateFields: ["POI_Group_ID", "POI_Group_Name"],
      allowedCreateFields: [
        "POI_Group_ID", "POI_Group_Name", "Group_Type", "Population", "Lore", "Image"
      ],
      allowedUpdateFields: ["POI_Group_Name", "Group_Type", "Population", "Lore", "Image"],
      assetField: "Image",
      assetFolderKey: "poiGroupImage"
    },

    map: {
      label: "Map",
      sheetName: "Maps",
      idField: "Map_ID",
      idPrefix: "MAP-",
      idPadding: 4,
      requiredCreateFields: ["Owner_Type", "Owner_ID_Ref", "Map_Name"],
      allowedCreateFields: [
        "Map_ID", "Owner_Type", "Owner_ID_Ref", "Map_Name", "Map_Type",
        "Image", "Sort_Order", "Lore"
      ],
      allowedUpdateFields: [
        "Owner_Type", "Owner_ID_Ref", "Map_Name", "Map_Type", "Image", "Sort_Order", "Lore"
      ],
      assetField: "Image",
      assetFolderKey: "mapImage"
    },

    npc: {
      label: "NPC",
      sheetName: "NPCs",
      idField: "NPC_ID",
      idPrefix: "NPC-",
      idPadding: 4,
      requiredCreateFields: ["Name"],
      allowedCreateFields: [
        "NPC_ID", "Home_ID_Ref", "Title", "Name", "Organization",
        "Race", "Occupation", "Lore", "Image"
      ],
      allowedUpdateFields: [
        "Home_ID_Ref", "Title", "Name", "Organization", "Race", "Occupation", "Lore", "Image"
      ],
      assetField: "Image",
      assetFolderKey: "npcImage"
    },

    dmJournal: {
      label: "DM Journal",
      sheetName: "DM_Journal",
      idField: "Entry_ID",
      idPrefix: "JRN-",
      idPadding: 5,
      requiredCreateFields: ["Entry_Body", "Entry_Type", "Source_Type", "Source_ID"],
      allowedCreateFields: [
        "Entry_ID", "Entry_Body", "Entry_Type", "Source_Type", "Source_ID",
        "Timestamp", "Created_By", "Session_ID", "Visibility"
      ],
      allowedUpdateFields: [
        "Entry_Body", "Entry_Type", "Source_Type", "Source_ID",
        "Timestamp", "Created_By", "Session_ID", "Visibility"
      ]
    }
  },

  entityAliases: {
    regions: "region",
    hexes: "hex",
    pois: "poi",
    poi_group: "poiGroup",
    poi_groups: "poiGroup",
    poigroup: "poiGroup",
    poigroups: "poiGroup",
    maps: "map",
    npcs: "npc",
    dm_journal: "dmJournal",
    dmjournal: "dmJournal",
    journal: "dmJournal"
  },

  allowedMimeTypes: [
    "image/png",
    "image/jpeg",
    "image/webp",
    "image/gif"
  ],

  maxUploadBytes: 10 * 1024 * 1024
};

function getKadeshConfig() {
  return KADESH_CONFIG;
}

function getScriptProperty_(key) {
  return PropertiesService.getScriptProperties().getProperty(key);
}

function requireScriptProperty_(key, label) {
  const value = getScriptProperty_(key);
  if (!value) {
    throw new Error(`Missing required ScriptProperty ${key}${label ? ` (${label})` : ""}.`);
  }
  return value;
}

function getSpreadsheetId_() {
  return requireScriptProperty_(KADESH_CONFIG.scriptProperties.spreadsheetId, "canonical Sheet ID");
}

function getFolderId_(folderKey) {
  const propertyKey = KADESH_CONFIG.scriptProperties.folders[folderKey] || KADESH_CONFIG.scriptProperties.folders.misc;
  return requireScriptProperty_(propertyKey, `${folderKey} Drive folder`);
}

function getEntityConfig_(entityType) {
  const rawKey = String(entityType || "").trim();
  const aliasKey = rawKey.toLowerCase();
  const key = KADESH_CONFIG.entityAliases[aliasKey] || rawKey;
  const entity = KADESH_CONFIG.entities[key];
  if (!entity) {
    throw new Error(`Unsupported entityType: ${entityType}`);
  }
  return entity;
}
