/**
 * Payload validation helpers for the Kadesh write-back prototype.
 */

function parseRequest_(event) {
  if (!event || !event.postData || !event.postData.contents) {
    throw new Error("Expected JSON POST body.");
  }

  try {
    return JSON.parse(event.postData.contents);
  } catch (error) {
    throw new Error(`Invalid JSON body: ${error.message}`);
  }
}

function assertObject_(value, label) {
  if (!value || Object.prototype.toString.call(value) !== "[object Object]" || Array.isArray(value)) {
    throw new Error(`${label} must be an object.`);
  }
}

function sanitizeString_(value) {
  if (value === null || value === undefined) return "";
  return String(value).trim();
}

function pickAllowedFields_(input, allowedFields) {
  assertObject_(input, "fields");

  const allowed = new Set(allowedFields);
  const output = {};
  const rejected = [];

  Object.keys(input).forEach(key => {
    if (!allowed.has(key)) {
      rejected.push(key);
      return;
    }
    output[key] = input[key];
  });

  if (rejected.length) {
    throw new Error(`Unsupported field(s): ${rejected.join(", ")}`);
  }

  return output;
}

function assertRequiredFields_(fields, requiredFields) {
  const missing = requiredFields.filter(field => sanitizeString_(fields[field]) === "");
  if (missing.length) {
    throw new Error(`Missing required field(s): ${missing.join(", ")}`);
  }
}

function validateCreatePayload_(payload) {
  assertObject_(payload, "payload");

  const entity = getEntityConfig_(payload.entityType);
  const fields = pickAllowedFields_(payload.fields || {}, entity.allowedCreateFields);
  assertRequiredFields_(fields, entity.requiredCreateFields);

  if (!entity.manualId && fields[entity.idField]) {
    throw new Error(`${entity.idField} is generated by the backend and should not be sent for create.`);
  }

  return { entity, fields };
}

function validateUpdatePayload_(payload) {
  assertObject_(payload, "payload");

  const entity = getEntityConfig_(payload.entityType);
  const id = sanitizeString_(payload.id);
  if (!id) {
    throw new Error("Update requires payload.id.");
  }

  const fields = pickAllowedFields_(payload.fields || {}, entity.allowedUpdateFields);
  if (!Object.keys(fields).length) {
    throw new Error("Update requires at least one allowed field.");
  }

  if (Object.prototype.hasOwnProperty.call(fields, entity.idField)) {
    throw new Error(`${entity.idField} cannot be updated.`);
  }

  return { entity, id, fields };
}

function validateUploadPayload_(payload) {
  assertObject_(payload, "payload");

  const entity = getEntityConfig_(payload.entityType || "map");
  const file = payload.file;
  assertObject_(file, "file");

  const name = sanitizeString_(file.name);
  const mimeType = sanitizeString_(file.mimeType);
  const base64 = sanitizeString_(file.base64);

  if (!name) throw new Error("file.name is required.");
  if (!mimeType) throw new Error("file.mimeType is required.");
  if (!base64) throw new Error("file.base64 is required.");

  if (KADESH_CONFIG.allowedMimeTypes.indexOf(mimeType) === -1) {
    throw new Error(`Unsupported mimeType: ${mimeType}`);
  }

  const approxBytes = Math.ceil(base64.length * 3 / 4);
  if (approxBytes > KADESH_CONFIG.maxUploadBytes) {
    throw new Error(`File exceeds max upload size of ${KADESH_CONFIG.maxUploadBytes} bytes.`);
  }

  return {
    entity,
    file: {
      name,
      mimeType,
      base64,
      description: sanitizeString_(file.description)
    },
    linkTo: payload.linkTo || null
  };
}

function validateJournalPayload_(payload) {
  const normalized = {
    entityType: "dmJournal",
    fields: payload.fields || {
      Source_Type: payload.sourceType,
      Source_ID: payload.sourceId,
      Entry_Type: payload.entryType || "note",
      Entry_Body: payload.body,
      Session_ID: payload.sessionId || "",
      Visibility: payload.visibility || (payload.playerVisible === true ? "player" : "dm")
    }
  };

  return validateCreatePayload_(normalized);
}

function requireAction_(payload) {
  const action = sanitizeString_(payload.action);
  if (!action) throw new Error("Request requires action.");
  return action;
}

function getActorEmail_() {
  const active = Session.getActiveUser && Session.getActiveUser().getEmail ? Session.getActiveUser().getEmail() : "";
  const effective = Session.getEffectiveUser && Session.getEffectiveUser().getEmail ? Session.getEffectiveUser().getEmail() : "";
  return sanitizeString_(active || effective);
}

function assertAuthorized_(payload) {
  const config = getKadeshConfig();
  const actorEmail = getActorEmail_();
  const allowedRaw = getScriptProperty_(config.scriptProperties.allowedWriters) || "";
  const allowed = allowedRaw.split(",").map(sanitizeString_).filter(Boolean).map(email => email.toLowerCase());
  const secret = getScriptProperty_(config.scriptProperties.sharedSecret);
  const providedSecret = sanitizeString_(payload && payload.secret);

  if (allowed.length && actorEmail && allowed.indexOf(actorEmail.toLowerCase()) !== -1) {
    return { actorEmail, mode: "session-email" };
  }

  if (secret && providedSecret && secret === providedSecret) {
    return { actorEmail: actorEmail || "shared-secret", mode: "shared-secret" };
  }

  if (!allowed.length && !secret) {
    throw new Error("No writer authorization configured. Set KADESH_ALLOWED_WRITERS or KADESH_SHARED_SECRET.");
  }

  throw new Error(`Unauthorized writer${actorEmail ? `: ${actorEmail}` : ""}.`);
}
